"""stellaML: model inference, orchestration, and data intelligence helpers."""

from stella_ml.analytics import (
    EDAReport,
    apply_cleaning_operations,
    auto_eda,
    explore_chart,
    explore_data,
    generate_bar_chart,
    infer_structure,
    load_and_impute_csv,
    load_tabular_file,
)
from stella_ml.automl import AutoMLPlan, choose_analysis_mode
from stella_ml.config import AgentProfile, StellaConfig
from stella_ml.feasibility import (
    ExperimentSpec,
    FeasibilityReport,
    HardwareProfile,
    autoimpute_experiment_specs,
    detect_local_hardware,
    generate_feasibility_chain,
    is_hardware_feasible,
)
from stella_ml.harness import HarnessResult, OpenClawStyleHarness, ProblemAssessment
from stella_ml.local_sota import (
    LocalModelRecommendation,
    ModelCandidate,
    ensure_huggingface_api_key,
    recommend_max_local_model,
    web_search_hf_sota,
)
from stella_ml.ml_backends import (
    BackendStatus,
    create_pytorch_mlp,
    create_tensorflow_mlp,
    demo_cuda,
    detect_backend_availability,
    install_packages,
    list_sklearn_estimators,
    recommend_cpu_sota_1bit_models,
    run_pymc_linear_regression,
)
from stella_ml.models import InferenceRequest, InferenceResponse, Message, Role
from stella_ml.orchestrator import AgentConfig, AgentRunResult, AgentRunner
from stella_ml.providers.base import BaseModelProvider, ProviderRegistry
from stella_ml.providers.huggingface import HuggingFaceProvider
from stella_ml.providers.openai_compatible import OpenAICompatibleProvider
from stella_ml.runtime import build_registry_for_agent
from stella_ml.unstructured import (
    TextEDAReport,
    UnstructuredDocument,
    autoeda_text,
    extract_unstructured,
    fetch_url_with_requests,
    fetch_url_with_selenium,
    ngrams,
    nltk_ngrams,
    parse_html_text,
    parse_pptx_text,
    parse_xml_text,
    run_unstructured_nlp_pipeline,
    spacy_entities,
)
from stella_ml.web_orchestration import (
    Skill,
    SkillCatalog,
    WebSearchResult,
    acquire_skills_from_results,
    web_search,
    web_search_orchestration,
)

__all__ = [
    "AgentConfig",
    "AgentProfile",
    "AgentRunResult",
    "AgentRunner",
    "AutoMLPlan",
    "BackendStatus",
    "BaseModelProvider",
    "EDAReport",
    "ExperimentSpec",
    "FeasibilityReport",
    "HarnessResult",
    "HardwareProfile",
    "HuggingFaceProvider",
    "InferenceRequest",
    "InferenceResponse",
    "LocalModelRecommendation",
    "Message",
    "ModelCandidate",
    "OpenAICompatibleProvider",
    "OpenClawStyleHarness",
    "ProblemAssessment",
    "ProviderRegistry",
    "Role",
    "Skill",
    "SkillCatalog",
    "StellaConfig",
    "TextEDAReport",
    "UnstructuredDocument",
    "WebSearchResult",
    "acquire_skills_from_results",
    "apply_cleaning_operations",
    "auto_eda",
    "autoeda_text",
    "autoimpute_experiment_specs",
    "build_registry_for_agent",
    "choose_analysis_mode",
    "create_pytorch_mlp",
    "create_tensorflow_mlp",
    "demo_cuda",
    "detect_backend_availability",
    "detect_local_hardware",
    "ensure_huggingface_api_key",
    "explore_chart",
    "explore_data",
    "extract_unstructured",
    "fetch_url_with_requests",
    "fetch_url_with_selenium",
    "generate_bar_chart",
    "generate_feasibility_chain",
    "infer_structure",
    "install_packages",
    "is_hardware_feasible",
    "list_sklearn_estimators",
    "load_and_impute_csv",
    "load_tabular_file",
    "ngrams",
    "nltk_ngrams",
    "parse_html_text",
    "parse_pptx_text",
    "parse_xml_text",
    "recommend_cpu_sota_1bit_models",
    "recommend_max_local_model",
    "run_pymc_linear_regression",
    "run_unstructured_nlp_pipeline",
    "spacy_entities",
    "web_search",
    "web_search_hf_sota",
    "web_search_orchestration",
]
